package org.example;

import org.example.repository.CrudRepository;
import org.example.util.ConnectionManager;
import org.postgresql.Driver;
import org.w3c.dom.ls.LSOutput;

import java.sql.*;

/**
 * Hello world!
 */
public class App {

    private static CrudRepository crudRepository = new CrudRepository();

    public static void main(String[] args) throws SQLException {
//        String sqlQuerySchema = "CREATE SCHEMA Clients";
//        String sqlQuery = "CREATE TABLE Clients.Consumers(" +
//                "id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " +
//                "name varchar(100) UNIQUE," +
//                "age int" +
//                ")";
//        String sql = "INSERT INTO Clients.Consumers(name,age) VALUES('Andrei', 28)";
//        String sql = "SELECT * FROM Clients.Consumers";
//        try (Connection connection = ConnectionManager.get(); Statement statement = connection.createStatement()) {
//            ResultSet consumers = statement.executeQuery(sql);
//            while (consumers.next()) {
//                System.out.println(consumers.getInt("id"));
//            }
        //            statement.executeUpdate(sql);
        //            statement.execute(sqlQuerySchema);
//        String sql = "SELECT * FROM Clients.Consumers WHERE id = ?";
//        try (Connection connection = ConnectionManager.get(); PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
//            preparedStatement.setLong(1, 1);
//            ResultSet resultSet = preparedStatement.executeQuery();
//            while(resultSet.next()){
//                System.out.println(resultSet.getString("name"));
//            }
//
////        }
        crudRepository.create("Andrei0", 28);
//        crudRepository.update(5, "Andrej", 29);
//        crudRepository.delete(5);
        System.out.println(crudRepository.getConsumer(6));
    }
}
